### ISSUE TITLE
R definition hangs and can't find repo

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-dev-containers#1032]
- VSCode Version: Version: 1.60.0-insider (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:40:58.134Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
- Local OS Version: Windows 11
- Reproduces in: Remote-Containers (haven't tried to repro in Codespaces) 
- Name of Dev Container Definition with Issue: R https://github.com/microsoft/vscode-dev-containers/tree/main/containers/r

Steps to Reproduce:

1. Add R definition to project
2. Reopen in container to build image
3. Build takes 5-10 minutes, then hangs and errors out

![image](https://user-images.githubusercontent.com/25310137/132038064-9f93510e-ab97-4f0d-b9a6-d8a48c15d311.png)

Seems like the relevant part is `"Cannot find repo ManuelHentschel/vscDebugger"` - I can see this repo is part of the Dockerfile: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/r/.devcontainer/Dockerfile#L36 and the repo still exists on GitHub (https://github.com/ManuelHentschel/vscDebugger), but I also see where [this repo was added/changed](https://github.com/microsoft/vscode-dev-containers/pull/1007/files#diff-e9c8b0b5da8948443c7cb67ce5344db0797dd706228b95d23b8b592601c1548eR36) in the Dockerfile as part of the recent [PR](https://github.com/microsoft/vscode-dev-containers/pull/1007). 

@eitsupi @kmehant Please let me know your thoughts, thank you!

**Comment by eitsupi** [comment]
As you can see in the error message displayed in the terminal, the access to `api.github.com` seems to have timed out.
Does this happen over and over again? Since this command alone constitutes the layer, I think that the second build will either give an error immediately or the build will be completed immediately.
(The first build takes about 10 minutes because it takes a long time to build the layers before this command.)

![image](https://user-images.githubusercontent.com/50911393/132043300-89f388ab-64e1-4d1e-80e2-df6c57bcf2e8.png)

I just tried it and it built without any problems. I also looked at the issues of [the remotes package](https://github.com/r-lib/remotes/issues) used to install the package from github repo, but there are not many similar reports, so the cause that comes to my mind is a temporary communication failure.

**Comment by bamurtaugh** [comment]
It happens consistently. @chrisdias tried this over two different days, and ran into the problem twice.

I just tried building the same project again that had failed from the screenshot, and after ~7 minutes got the same error:

![image](https://user-images.githubusercontent.com/25310137/132045640-1bfb6196-8736-4199-9e15-a7214945df88.png)

I clicked "Retry" and it seems to have worked now:

![image](https://user-images.githubusercontent.com/25310137/132045888-08b4bc64-2d69-420b-a490-be89450ba4dc.png)

But as an end user, after waiting up to 10 minutes for that initial error, I wouldn't be inclined to click "Retry" (Chris and I weren't when we ran into this). What can we do to mitigate that initial error?

**Comment by eitsupi** [comment]
Do you think it could be due to restricted access to the GitHub API?
In other words, this session is anonymous access, but is there a lot of other token-based access that could be the cause?

**Comment by eitsupi** [comment]
> I just tried building the same project again that had failed from the screenshot, and after ~7 minutes got the same error:

I'm sorry, I wasn't sure exactly if the layer cache was used in the build with Remote-Containers.

> But as an end user, after waiting up to 10 minutes for that initial error, I wouldn't be inclined to click "Retry" (Chris and I weren't when we ran into this). What can we do to mitigate that initial error?

I can only think of commenting out the installation command that is causing it.

@ManuelHentschel @renkun-ken Any idea?

**Comment by Chuxel** [comment]
Yeah rate limiting on api.github.com can be very difficult to predict In a cloud environment - particularly anonymous like you'd see in a Dockerfile (which lowers limits). IPs get reused, so you can hit situations where it stops working.  I generally try to avoid their use because of it in favor of other techniques.  I even use the `git` CLI to do things like finding release tags to stay away from the APIs at scale.

**Comment by eitsupi** [comment]
Thank you for your suggestion.
It seems that we can get the latest tag without the GitHub API with the following command, so I would like to update the Dockerfile to use this.

```shell
$ git ls-remote --tags https://github.com/ManuelHentschel/vscDebugger | tail -n 1 | cut --delimiter='/' --fields=3
v0.4.7
```
