### ISSUE TITLE
Improved NVM support

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-dev-containers#1046]
This issue is a wider-ranging successor to #879, which got a bit off-topic.

I find NVM is the best way to get control of a shared Node.js version between development and build/production environments. In a perfect world I'd specify a Debian or Ubuntu container image, drop in an `.nvmrc`, and maybe run one post-install command.

Two potential areas to improve right now:

1. Every container rebuild causes NVM to download Node.js again.
1. Every terminal session begins with an NVM warning.

The first one is described more fully in #879, along with an effective workaround in https://github.com/microsoft/vscode-dev-containers/issues/879#issuecomment-866409825. But out-of-the-box support (including Codespaces, which I don't think allows local mounts) would be great.

For the second one, I think this warning may be a recent addition to NVM:

<details>

```
Your user’s .npmrc file (${HOME}/.npmrc)
has a `globalconfig` and/or a `prefix` setting, which are incompatible with nvm.
Run `nvm use --delete-prefix v16.9.1 --silent` to unset it.
```

</details>

My workaround is to add `nvm use --delete-prefix` to my `"postCreateCommand": ".devcontainer/install.sh"`, though I admit I don't know if this has other impacts:

```sh
#!/bin/zsh -i

# Install Node.js version defined in .nvmrc
nvm install
nvm use --delete-prefix

# Install project dependencies from lockfile
yarn install --immutable
```

In terms of problem set and potential solutions, there may be significant overlap between the above and https://github.com/microsoft/vscode-dev-containers/issues/618#issuecomment-879042944.

**Comment by Chuxel** [comment]
One of the things we're hoping to release soon is UX that allows you to add additional "features" to base images. (See https://github.com/microsoft/vscode-remote-release/issues/5442, https://github.com/microsoft/vscode-dev-containers/issues/1044).  

This will allow you to pick a Ubuntu or Debian base image (the Debian or Ubuntu definition here), and then check a checkbox to get nvm and yarn installed. This should simplify scenarios where you what you really want is a customized image rather than one that is ready made with common dependencies.

Would that meet your needs?

In general, `--delete-prefix` is totally fine. That's there because of the globally installed eslint, tslint, but given these weren't things you wanted either from another issue, I suspect this model would work well for you.

FWIW - The bulk of the image size is not node, but rather the contents of `buildpack-deps` to enable things like `node-gyp` to work out of box.

//cc: @joshspicer @chrmarti @2percentsilk on the input.

**Comment by Chuxel** [comment]
Dev container "features" support is available in preview, so what I describe here should be possible now.  Would love to know if you can now create a custom environment from one of the base images that better meets your needs.

**Comment by aaronadamsCA** [comment]
This new features support is very interesting! I've tried it out and it seems like a solid idea.

I expect we'll migrate to this solution, but I also foresee challenges after we do so. The configuration in `devcontainer.json` instead of `Dockerfile` seems to block the use of other features, like Docker Compose.

I'd eventually like our workspace container to be able to run sibling containers (e.g. MongoDB and Ngrok) **on demand**, configured in `docker-compose.yml`. This could allow us to significantly shrink our base image by excluding these large utilities until they're needed by the subset of developers who use them.

Migrating to container features in their current state would seem to block that.

Still, given there's now good support for building a much leaner base image with NVM support, I'm comfortable calling this specific issue closed, with the above feedback in mind. Thanks!

**Comment by Chuxel** [comment]
Sounds good!  But FYI, features also work with Docker Compose definitions. They'll apply to the service you reference.

**Comment by aaronadamsCA** [comment]
Ah, interesting. Thanks for that @Chuxel, I'll keep looking into it.
