### ISSUE TITLE
Consider moving to Microsoft OpenJDK builds

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#1050]
Currently the "java" definition uses AdoptOpenJDK.  Microsoft now has builds for JDK 11 and 16 we could use instead.

https://docs.microsoft.com/en-us/java/openjdk/containers

@akaroml @testforstephen - Would this be the VS Code Java team's go forward recommendation?

//cc: @joshspicer

**Comment by testforstephen** [comment]
For Java on Azure, we recommend using Microsoft OpenJDK. For running on a user's machine, we don't force user what JDK to install. Switching to Microsoft OpenJDK in the generic Java container template, I don't know if users have licensing concerns.

**Comment by mwiede** [comment]
When will java 17 come as `mcr.microsoft.com/vscode/devcontainers/java:0-17` ?

**Comment by Chuxel** [comment]
Off topic for this thread, but @testforstephen, when should we add java 17 to the mix?  Do the Java extensions support it yet?

**Comment by brunoborges** [comment]
There is absolutely no concern. The license of the Microsoft Build of OpenJDK is the same as AdoptOpenJDK, simply because all these binaries are based on the same source code licensed under GPL2+CE.

In fact, here are important things to address:

1. AdoptOpenJDK may no longer see updated JDKs in the future. The project has moved to [Adoptium.net](https://adoptium.net) and the binaries are built and published at a different URL.
1. Only the devcontainers for Java 8 and Java 11 are based on binaries built under the AdoptOpenJDK project.
1. The devcontainer for 16 is a binary from Oracle OpenjDK published at [jdk.java.net](https://jdk.java.net).
1. The base image of the Java devcontainers is the one [/_/openjdk](https://hub.docker.com/_/openjdk) maintained by "the Docker Community", and this means we have zero, absolutely no control of what goes into the base image of the devcontainer for Java across all three versions currently maintained. Therefore, we are open to issues regarding the supply chain of software we ourselves are offering to end users.

Disclaimer: I'm the PM for the MS Build of OpenJDK.

**Comment by Chuxel** [comment]
@brunoborges  Sounds good. What should happen with JDK 8?

@akaroml @testforstephen Could you PR as appropriate?

/cc: @joshspicer since we probably want to adjust what the Java script defaults to based on this.

**Comment by Chuxel** [comment]
@brunoborges One other question - is there a bullseye image available for Java?  Otherwise this won't work on M1 Macs which is a concern here.

**Comment by brunoborges** [comment]
> If not, then the PR probably should be to base off of `mcr.microsoft.com/vscode/devcontainers/base` and install the JDK separately is what I am wondering here.

Yes, that's how it should be done. Given its Debian, you have two options: either COPY from our image the already-insyalled JDK path, or use the Debian I stallation with APT. Both are documented in our site.

**Comment by brunoborges** [comment]
Regarding Java 8, I don't think you really need to have a separate base image for that. Just add a flow the same way you already have for Grade/Maven, and if the user wants, JDK 8 gets installed and configured.

**Comment by Chuxel** [comment]
Also /cc @2percentsilk @bamurtaugh for visibility.

**Comment by testforstephen** [comment]
Java 17 support in VS Code Java extension is not released yet. It's scheduled to release in a couple weeks. After that, we'll add JDK 17 to devcontainer template and also fix the JDK issues mentioned above.

**Comment by cemo** [comment]
@testforstephen which extension is not supporting JDK 17 yet?

**Comment by testforstephen** [comment]
@cemo Extension Pack for Java: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack

**Comment by brunoborges** [comment]
Hey @testforstephen, can you be more specific please? Which extension in the pack does not work?

**Comment by testforstephen** [comment]
It's **Language Support for Java by Red Hat**, which will release a new version for Java 17 support soon. The planned new version is next week, please stay tuned.

Since the extensions in VS Code Java Pack work together to provide full language support for Java. If RedHat Java language support fails in JDK 17, then other extensions such as **Debugger for Java** won't work either.

**Comment by Chuxel** [comment]
Another issue I'm noticing is that there's no arm64 builds for the JDK images and there doesn't seem to be packages for Debian bullseye yet for installing via a `.deb`. This combination is needed for M1 Mac support.  We'd likely need to instead go `FROM mcr.microsoft.com/vscode/devcontainers/base:bullseye` and manually set it up via `tar.gz`.

**Comment by cemo** [comment]
Since #1113 has merged, Is it ready to use right now @Chuxel ?

**Comment by Chuxel** [comment]
@cemo No. That queues up 17 - there is a dev image (`mcr.microsoft.com/vscode/devcontainers/java:dev-17`), but its unclear if this would work with the extension given what @testforstephen has said. You can give it a shot if you'd like, however.

**Comment by testforstephen** [comment]
That's dev branch, it's code is ready but not yet released to the marketplace.
