### ISSUE TITLE
What is the Proper Way to Set `INSTALL_ZSH` as `False`

### ISSUE THREAD

**Issue by taicaile** [microsoft/vscode-dev-containers#1144]
https://github.com/microsoft/vscode-dev-containers/blob/f173f722e3819008c0b93af50e5c9aacff510dae/containers/ubuntu/.devcontainer/base.Dockerfile#L1-L6
Hello, I would like to know if it is possible not to install ZSH.

I have tried to add the following to `.devcontainer/Dockerfile`,
```dockerfile
ARG INSTALL_ZSH="false"
```
It did not work.

Also tried to add the following to `.devcontainer/devcontainer.json`,
```json
"INSTALL_ZSH": "false"
```
This didn't work too.

**Comment by Chuxel** [comment]
@taicaile It's possible possible if you build from scratch.  The `base.Dockerfile` is used to generate the pre-built image. To build from scratch, update `devcontainer.json` to reference `base.Dockerfile` and either update base.Dockerfile and or devcontainer.json.

It's in the pre-built image already otherwise.
