### ISSUE TITLE
.NET 6.0 Release?

### ISSUE THREAD

**Issue by davegoopot** [microsoft/vscode-dev-containers#1154]
What are the plans for getting the .NET 6.0 release set up with the Codespace/dev container please?

Relates to: Both

**Comment by Chuxel** [comment]
Queued up a PR for the mcr.microsoft.com/vscode/devcontainers/dotnet:6.0 image.  It already exists but is RC.

@joshspicer - Can you work with Oryx on the universal image?  I believe 6.0 is already getting auto installed, but we probably need to pick a point to switch to 6.0 being there by default.

**Comment by Chuxel** [comment]
`mcr.microsoft.com/vscode/devcontainers/dotnet:6.0` is updated now.

Re-opening for `universal` image.

**Comment by davegoopot** [comment]
Working like a dream for me here. New codespace showing version 6.0.100.

Is the done thing for me to close this ticket?

**Comment by joshspicer** [comment]
@davegoopot  - Great! That is probably being auto-installed by Oryx since I'm guessing your repository contents are heavily .NET. We'll keep this issue open for a little longer while we pre-cache dotnet 6 without the need to dynamic install. Right now we are precaching these version.

![image](https://user-images.githubusercontent.com/23246594/141010838-1a34f731-a350-4106-b80d-6c3da5af2ada.png)

**Comment by joshspicer** [comment]
assigning to myself while we await the oryx update.
