### ISSUE TITLE
Pass additional parameters to container

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode-dev-containers#1258]
I love this extension!

I am an embedded developer, and I desperately need the ability to "flash" binaries from my containerized development environment as well as use a debugger (both functions are usually performed via a USB peripheral). I normally accomplish this by creating the appropriate `udev` files in my container, and provide `--device /dev/bus/usb` parameter to the `docker` call on the command line.

All I need from this extension is a simple way to pass additional parameters to the `docker` command, but I can't find anything in `devcontainer.json` to allow me to supply them.

Relates to: Remote - Containers

**Comment by zfields** [comment]
Okay, I can see that `"runArgs": [ "--device=/dev/bus/usb/" ],` in `.devcontainer/devcontainer.json` does allow me to do just that.

One odd observation, is that the above syntax works, but `"runArgs": [ "--device /dev/bus/usb/" ],` fails.

It absolutely requires the `=`, although the `docker` command line does not.

**Comment by Chuxel** [comment]
@zfields The space in a command line results in it being two separate args.  So I'd expect these two variations to work:

`"runArgs": [ "--device=/dev/bus/usb/" ]`

and

`"runArgs": [ "--device", "/dev/bus/usb/" ]`.

The problem is `--device /dev/bus/usb/` is passed into docker as a single argument... like to the array syntax for ENTRYPOINT or CMD in Dockerfiles.

**Comment by zfields** [comment]
I understand what's happening now. Thanks for the detailed explanation!
