### ISSUE TITLE
completely remove official docker for mac and use lightweight linux VM instead

### ISSUE THREAD

**Issue by lucaszanella** [microsoft/vscode-dev-containers#1313]
I've been trying to develop on mac and it's beeing a real pain because of the slowness of docker even with all the delegated volumes and stuff. Simple buids that take 3 or 4 minutes on linux are taking 40 minutes on mac, even on M1 mac.

I think it would be nice to have a second option as like running a separate VM with a copy of the project, and when you close it, the modified copy is sent back. Something like that. Because it's impossible to work on mac using devcontainers :(

**Comment by Chuxel** [comment]
@lucaszanella Off topic for this repository, but a few tips here. You can likely already do what you're thinking about:

A few general tips:
1. M1 macs may be running the image emulated because only x86 is available. That will cause significant slowness all up.
2. Make sure your Docker VM has enough capacity and RAM assigned.  The default of 2 core and 2GB is rarely enough.
3. Try the Clone Repository in Container Volume option since this puts the disk in a Volume instead of the local file system - https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume

For your own VM (whether local or in the cloud), you can use Remote - SSH + Remote Containers together, either locally or remotely.  See https://code.visualstudio.com/docs/remote/containers#_open-a-folder-on-a-remote-ssh-host-in-a-container

Closing as off-topic for the repo, but hopefully that helps. You can also check out https://code.visualstudio.com/remote/advancedcontainers/improve-performance
