### ISSUE TITLE
Install less in all definitions for git log

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#230]
Currently "less" is not present in all scenarios which can cause git log to error. This should be added to the common script and any definition that does not use it.

**Comment by yoloVoe** [comment]
I encountered this issue when using dev containers with a custom Dockerfile & zsh.

Just FYI to anyone else out there, if `git log` keeps printing all your commits w/o stop (seemingly scrolling forever if you have a long commit history), then the issue is probably that you don't have the `less` command.

Try typing `less`. Do you see a command not found?

If so, install `less` and then try `git log`.
