### ISSUE TITLE
tomcat 404 but war running!

### ISSUE THREAD

**Issue by sungle3737** [microsoft/vscode-dev-containers#282]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.
![image](https://user-images.githubusercontent.com/27716524/79198313-40fc4b80-7e6e-11ea-99f1-5db338ad3370.png)
- my mvn version in here

![ss](https://user-images.githubusercontent.com/27716524/79198399-60937400-7e6e-11ea-8888-2e7eabed9ff1.gif)
And there is routing in tomcat but there is only 404

### I can't find why this issue happen!!

- my server log is here
[log.log](https://github.com/microsoft/vscode-dev-containers/files/4473969/log.log)

**Comment by Chuxel** [comment]
This is a bit off topic for this repository, but it looks like the config for the application you deployed is incorrect from the logs. You can see it complaining about values in the XML. It's possible there is some sort of encoding issue with the XML file or you've put reserved characters into the XML file.

For example, this error makes me think that this may be the case - if you've got `<` in the password value (either because of a mistake or encoding), the deploy will bomb.

```
[tomcat]: Apr 14, 2020 8:04:53 AM org.apache.naming.NamingContext lookup
WARNING: Unexpected exception resolving reference
org.xml.sax.SAXParseException; lineNumber: 40; columnNumber: 37; The value of attribute "password" associated with an element type "user" must not contain the '<' character.
```

**Comment by sungle3737** [comment]
Thanks for kind answer! it really helped
