### ISSUE TITLE
how to set custom container name in devcontainer.json

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-dev-containers#287]
Hello, when I open a folder with devcontainer.json, I get a container which has random name like " friendly_driscoll".

How to set custom container name? or Let VSCode use my existing container? (not existing image)

How does VSCode relate the folder to a container? 

Thanks,

**Comment by Chuxel** [comment]
The good news is that this is being explored this iteration.  See https://github.com/microsoft/vscode-remote-release/issues/3198 https://github.com/microsoft/vscode-remote-release/issues/2485, https://github.com/microsoft/vscode-remote-release/issues/1785 for information on progress.

Closing as a duplicate since the vscode-remote-release repository is the right place for this particular topic.
