### ISSUE TITLE
Tensorflow devcontainer

### ISSUE THREAD

**Issue by bhack** [microsoft/vscode-dev-containers#377]
I am trying to prepare a configuration to contribute for Tensorflow.
As you can from https://github.com/tensorflow/build/issues/8#issuecomment-646081197 I am using the official developer image with `-u $(id -u):$(id -g)` cause we don't have an existing non root user in the official image. 
This is working fine for a manual build inside the container.

Instead for `.devcontainer` I've tried to use `"remoteUser"` and `"containerUser" but in both cases it find permission problem with `/root`.

**Comment by Chuxel** [comment]
@bhack If that user doesn't actually exist in the image, it will fall back to using root. (The `-u` argument doesn't create the user.) Is this related to your PR (https://github.com/microsoft/vscode-dev-containers/pull/347)?  

Your Dockerfile includes `vscode` user, so that should work there. The Remote - Containers functionality will run commands to modify the GID/UID of the specified user to the local ones. There's no real out of box way to do this without a Dockerfile which is why the custom functionality exists.

**Comment by bhack** [comment]
It is not related to (#347) but to a WIP for Tensorflow itself. I would like to not make another Dockerfile wrapper as for Tensorflow addons. 
But It seems that there Is no solution if we want to have a non root user over the official Tensorflow devel image.

**Comment by Chuxel** [comment]
@bhack Yes, unfortunately that is the case.

Closing given I think I covered the answer here, but LMK if you have further questions.

**Comment by bhack** [comment]
@Chuxel check https://github.com/microsoft/vscode-dev-containers/pull/381
