### ISSUE TITLE
Add optional node install for all definitions with languages commonly used for web development

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#470]
Given node's prevalence in front-end web development, it is common to need node in addition to another language used for back-end development. We can provide an `ARG` to allow developers to opt in/out of adding node to the container from `devcontainer.json`.

- [x] dotnecore, dotnetcore-fsharp
- [ ] <strike>dapr-*</strike>
- [x] go
- [x] php, php-mariadb
- [x] python-3, python-3-*
- [x] java
- [x] ruby, ruby-*, jekyll
- [x] swift
- [ ] <strike> azure-functions-* (?)</strike>
- [x] azure-static-web-apps

Several others need Node (e.g. azure-terraform, elm), but that's already covered.

**Comment by mrjoshuak** [comment]
First of all thanks for all the work on these standardized development containers.  

I have some notes regarding the Go containers. 

It is not at all common to use Node.js as a frontend for Go.  In fact I've never seen it in any professional go deployment environment ever. 

The [readme][1] says: 

"Given how frequently Ruby-based web applications use Node.js for front end code, this container also includes Node.js."

Clearly, one would say "Go-based" here instead of "Ruby-based" for this Go version, except that as soon as you do the statement becomes obviously ridiculous.

Would it not make more sense for each language server to exist in its own repo with native language maintainers?

I would think one would want the standard dev-server definitions provided here to be as minimalistic as possible given that users of the containers are free to add their own additional requirements? It is somewhat easer to add layers to a container than to remove them. 

[1]: https://github.com/microsoft/vscode-dev-containers/blob/master/containers/go/README.md

**Comment by Chuxel** [comment]
@mrjoshuak Thanks, that's actually partly a doc bug. New edit:

> Given Node.js is often used with for front-end web client code used in conjunction with a Go back-end, this container also includes `nvm` so that you can easily install Node.js. 

Only nvm is present, but this came up enough in conversations that we added it. That said, we're thinking through [alternate approaches](https://github.com/microsoft/vscode-dev-containers/issues/615#issuecomment-718479364) for people to create their own multi-stack containers since this can get quickly out of hand.
