### ISSUE TITLE
nvm not available in postCreateCommand (Codespaces)

### ISSUE THREAD

**Issue by mchelen-gov** [microsoft/vscode-dev-containers#559]
- VSCode Version:  Version: 1.49.0-insider
- Name of Dev Container Definition with Issue: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/codespaces-linux

Steps to Reproduce:

1. Create `.devcontainer/devcontainer.json` with:
```json
{
  "postCreateCommand": "nvm install --lts"
}
```
2. In creation logs "Configure Codespace"
```
[VS Online][6cf65c38-13d9-404d-831a-906b7f1dc467] /home/codespace/.vsonline/.cloudenv-scripts/postCreateCommand.sh: line 3: nvm: command not found
```
3. Same problem using full path `/usr/local/share/nvm`

```
[VS Online][99d87f4e-2d70-4180-af85-38c8d746008f] /home/codespace/.vsonline/.cloudenv-scripts/postCreateCommand.sh: line 3: /usr/local/share/nvm: No such file or directory
```

**Comment by Chuxel** [comment]
@mchelen-gov Thanks for raising the issue!

I think this is happening since postCreateCommand runs as a non-interactive, non-login shell.  nvm is really particular that it needs to be "sourced" before it is used - which can only be done from interactive or login shells (via an rc or profile file). 

Try doing the following instead:

```bash
"postCreateCommand": "bash -i -c 'nvm install --lts'"
```

The following should also work:

```bash
"postCreateCommand": "source $NVM_DIR/nvm.sh && nvm install --lts"
```

The image has "symlink mode" enabled in nvm so the "current" version of Node is always in the path for that reason. That doesn't make nvm itself work, sadly.

Does that help?

**Comment by mchelen-gov** [comment]
@Chuxel that works, thank you for explaining! i went with the second option because this is running in a `post-create.sh` script

**Comment by Chuxel** [comment]
@mchelen-gov Great!  Another trick you can use in a script is `#!/bin/bash -i` which will run the entire script interactively.  Note that if you want login scripts to fire too, you can do `-l` instead of `-i`.

I'll take a to-do to add some of this into docs and the default devcontainer.json files to raise visibility a bit.  Closing as resolved otherwise.

**Comment by aaronadamsCA** [comment]
Friendly note for anyone coming across this later like I did.

This didn't work in a shell script for me, because it seems that regardless of sourcing, `nvm` still demands to be run interactively:

```sh
. $NVM_DIR/nvm.sh && nvm install
```

The only thing that worked was to change the hashbang to `#!/bin/bash -i` (or `#!/bin/zsh -i`), then `nvm install` worked on its own.

**Comment by Chuxel** [comment]
Yeah this is a good catch.  Since the default shell can be `sh`, you should use `.` instead of `source`. They both result in the same thing, but the `source` keyword is missing from sh (or more specifically dash/ash).
