### ISSUE TITLE
Add an option to install fish shell

### ISSUE THREAD

**Issue by andreiborisov** [microsoft/vscode-dev-containers#570]
I would like to be able to install and use fish shell alongside Zsh in dev containers.

Are you willing to review a PR for this?

**Comment by Chuxel** [comment]
The challenge is that, given fish's incompatibility with things like `nvm` that are in many of the dev containers here, I don't think we can include it by default since that would set the wrong expectation.  So I wouldn't  want to include it in the `common-debian.sh` script for example. zsh is compatible enough with bash / sh that it tends not to have these problems. However, if you'd like to PR  a separate script for setting up fish that developers could opt into using, that sounds good to me!

**Comment by andreiborisov** [comment]
We can still include it in `common-debian.sh`, but hide it behind a flag (don’t install it by default).
