### ISSUE TITLE
PowerShell (5.1) (Windows) Container

### ISSUE THREAD

**Issue by kilasuit** [microsoft/vscode-dev-containers#596]
Add a Windows based devcontainer for older PowerShell development needs where developing for PowerShell 7 isn't possible

**Comment by Chuxel** [comment]
Thanks for the issue!  Unfortunately, there isn't a PowerShell container image for versions earlier than 6. We also don't currently support windows containers (see https://github.com/microsoft/vscode-remote-release/issues/445).  As a result, I don't know that we'll really be able to do this realistically. I'm going to close this as "upstream" since both of these would need to change before we could pick anything up.

**Comment by kilasuit** [comment]
@Chuxel actually there is - it would need to use the WindowsServerCore image & would only be viable on windows machines

I am happy to add in a container for this (& add that it will be Windows only) but wanted to see if this would be accepted before spending too much time on it?

The key scenario would not be for use in codespaces but local remote development containers.

**Comment by Chuxel** [comment]
@kilasuit Yeah, Remote - Containers (local) doesn't support WindowsServerCore images (that's  microsoft/vscode-remote-release#445 above). It fires shell commands to do what it needs to do to get up and running, so I'd expect it to fail. LCOW also had issues due to missing features at the time.
