### ISSUE TITLE
Unable to use Docker with "vscode" use in Azure Functions Python definition

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#608]
@TsuyoshiUshio @anthonychu As a part of looking at switching defaults from "root" to a non-root user for definitions in this repository (#552), I noticed that the Azure Functions Python image includes Docker, but unfortunately there are a number of scenarios where the `vscode` user can't access it including from Docker Desktop or in Codespaces.

There's now a [docker common script](https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/docker.md) that progressively uses different approaches from simple to complex to ensure the socket is available.

How important is Docker to the scenario?  If you'd like, you could update the image, we could keep things as `root` by default, or use `vscode` as the default.  Thoughts?

**Comment by anthonychu** [comment]
I think this is less important now. It was needed in the past to run a build in a container so that the correct dependencies are installed into the app package that is deployed. We now have remote build option and I believe the VS Code Azure Functions extension defaults to this now. It's probably okay to remove.

**Comment by Chuxel** [comment]
Sounds good!  Will remove the socket reference to keep that clear when I update the default user.  Closing!
