### ISSUE TITLE
Cannot install new .NET SDK versions in Docker images

### ISSUE THREAD

**Issue by tomhamming** [microsoft/vscode-dev-containers#658]
I'm not sure where the best place to ask this is...I'm starting here to get a pair of human eyes on it.

I use the [default Linux universal](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/codespaces-linux) image for development using .NET and Android SDKs. A coworker recently updated us to use .NET 5 using a `global.json` file and then promptly left the company, and now any time I do anything with `dotnet` in the container it complains about not having the right SDK installed:

 > A compatible installed .NET Core SDK for global.json version [5.0.100] from [/home/codespace/workspace/global.json] was not found Install the [5.0.100] .NET Core SDK or update [/home/codespace/workspace/global.json] with an installed .NET Core SDK: 1.1.14 [/home/codespace/.dotnet/sdk] 2.1.807 [/home/codespace/.dotnet/sdk] 2.2.402 [/home/codespace/.dotnet/sdk] 3.0.103 [/home/codespace/.dotnet/sdk] 3.1.301 [/home/codespace/.dotnet/sdk]

Is there a way to install the .NET 5 SDK in this image from the command line? Or does the base image need to get updated to include .NET 5?

A very similar question [exists](https://stackoverflow.com/questions/60946711/how-to-add-additional-sdk-versions-to-net-docker-image) unanswered on Stack Overflow.

**Comment by Chuxel** [comment]
We're looking to add it with this update: https://github.com/microsoft/vscode-dev-containers/issues/623

The `.dotnet` folder in the user home directory is setup to be the SDK location, so should be able extract the Linux download in that location. Here's a one-line command:

```bash
curl -sSL 'https://download.visualstudio.microsoft.com/download/pr/820db713-c9a5-466e-b72a-16f2f5ed00e2/628aa2a75f6aa270e77f4a83b3742fb8/dotnet-sdk-5.0.100-linux-x64.tar.gz' | tar -xzC ~/.dotnet
```

There is a custom dev container that is focused on .NET as well that we just released a 5.0 variant if you prefer. If you use the "Add Development Container Configuration Files" command from the command palette (F1), just update devcontainer.json to reference "5.0" instead of "3.1". You can also manually copy just `Dockerfile` and `devcontainer.json` from [here](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet/.devcontainer).

**Comment by tomhamming** [comment]
Thanks @Chuxel ! That seems to work.

For the sake of my understanding, what determines what versions of the SDK are installed on a freshly created image? I looked through the various scripts and configuration files for the image I linked to in this repo and I can't find anything that seems to specify .NET version(s).

**Comment by Chuxel** [comment]
The `codespaces-linux` image inherits from `microsoft/oryx/build` (which is used by app service and enables the buildpack-like behavior of the image). 

Here's the related issue on .NET 5: https://github.com/microsoft/Oryx/issues/843

If we need to get something out faster, we do have the option of temporarily installing via other means in the codespaces-linux image. (e.g. Java and Ruby are in the latest image, but we installed those manually in the interim).
