### ISSUE TITLE
Docker-From-Docker Windows paths

### ISSUE THREAD

**Issue by sti0** [microsoft/vscode-dev-containers#716]
- VSCode Version: 1.52.1
- Local OS Version: Windows 10 Pro 1903
- Name of Dev Container Definition with Issue: Docker-From-Docker

Steps to Reproduce:

1. Add entry `"remoteEnv": { "LOCAL_WORKSPACE_FOLDER": "${localWorkspaceFolder}" }` to `devcontainer.json` on
2. Running VSCode on Windows and enter the devcontainer
3. `echo $LOCAL_WORKSPACE_FOLDER` -> `c:\Some\path\to\project\folder`
4. Execute `docker run --rm -it -v ${LOCAL_WORKSPACE_FOLDER}:/test alpine ls -la /test`
5. Error `docker: Error response from daemon: invalid mode: /test.`

This happens because there is a colon in the Windows path. 

How to get this to work? How to bind the host Windows paths within the container?

**Comment by 2percentsilk** [comment]
Hi @sti0,

I'd suggest checking out the new docker-in-docker definition, since it will not have these bind mount problems. We'd love to hear feedback on how that goes! 

On our side, we'll need to update our docs after we figure out the recommended/easiest way to solve the incorrectly escaped chars issue. It is indeed that colon causing you issues.

**Comment by sti0** [comment]
Hey @2percentsilk ,
thanks for the workaround. This solves not this issue but it works for my use case.

BR

**Comment by Chuxel** [comment]
For the docker-from-docker case, use this syntax:

```bash
docker run --rm -it -v ${LOCAL_WORKSPACE_FOLDER//\\/\/}:/test alpine ls -la /test
```

This will flip each `\` in the path to `/` which is the correct syntax for Docker in this case.

Will update the READMEs as well.
