### ISSUE TITLE
Add "Pylance" as python language server

### ISSUE THREAD

**Issue by yashgorana** [microsoft/vscode-dev-containers#723]
Pylance has some pretty impressive features which I feel is a must-have in any python dev environment. Also being developed by Microsoft, it makes sense to have it installed in the Python dev container.

This will require two changes
1. Adding "ms-python.vscode-pylance" to list of extensions installed
2. Updating settings to "python.languageServer": "Pylance"

**Comment by bamurtaugh** [comment]
cc @savannahostrowski Is there anything else that'd need to be added/should be considered in a dev container with Pylance? Are there still scenarios where it makes sense for a Python environment not to have Pylance?

**Comment by savannahostrowski** [comment]
@bamurtaugh Pylance covers all workloads at this point. Nothing else should be needed. Because Pylance is an optional dependency for a Python workload (with the core extension being effectively required), the user of course has the option to use any language server of their choosing still, even if we include Pylance. They could simply change python.languageServer to something else (e.g. "Microsoft" or "Jedi").

cc: @luabud for visibility

**Comment by bamurtaugh** [comment]
Thanks for the info @savannahostrowski! Do you think updating the dev container definition to use Pylance by default makes sense then?

**Comment by savannahostrowski** [comment]
If you are able to specify Pylance as the default language server in the configuration of the container, yes. 🙂

**Comment by luabud** [comment]
Agreed! 🥳

**Comment by bamurtaugh** [comment]
Thanks for the insight @savannahostrowski @luabud 😄. 

@yashgorana Since the Pylance/Python folks think updating to Pylance makes sense as well, do you want to try creating a PR with the updates you mention? :)

**Comment by yashgorana** [comment]
@bamurtaugh I've created a PR. I've limited the scope to modify just the "python-3" dev container. I can update it for other python3 related containers if required:
- `python-3-anaconda`
- `python-3-miniconda`
- `python-3-postgres`
- `python-3-device-simulator-express`
