### ISSUE TITLE
Switch to using Linux package managers to acquire kubectl, helm, GitHub CLI

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#751]
There are a few spots in scripts in this repository that use curl to download a utility even when native Linux package manager support is available. Using apt-get has the added benefit of improved security due to signing and easier and simplified upgrades to the packages.

In particular, the following can be switched:

- [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-native-package-management)
- [helm](https://helm.sh/docs/intro/install/#from-apt-debianubuntu)
- [The GitHub CLI](https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-apt)
- [Terraform](https://www.terraform.io/docs/cli/install/apt.html)

**Comment by PavelSosin-320** [comment]
Only apt-get ? Yum, dnf, rpm, zyper ??? Depends on the distro.  Linux is not only Ubuntu. Mainly, not Ubuntu in the enterprise software development world. Some tools are released as apt packages with 1/2 year delay or never if Corp's don't like apparmor.

**Comment by Chuxel** [comment]
@PavelSosin-320 This repository contains opinionated starting points all of which currently use debian or ubuntu as their base images (with one Alpine image being the exception). I agree with your two year comment however, which is why the installation directions linked in the description involve a 3rd party apt repository. The scripts in question are also suffixed with "-debian" to make it clear.

That said, it's certainly reasonable to use the Remote - Containers extensions or Codespaces with an image sourced from one of this distributions. This is not making any statement around that general topic.

**Comment by PavelSosin-320** [comment]
@Chuxel There is no general Linux package manager for Linux like Windows upgrade. It is also necessary to use apt/rpm/dnf/yum upgrade before apt-get. Otherwise, the scripts can't be corrected and versioned. The result of the update can be "Everything has been resolved"
Every package manager has its own configuration too. Podman uses a separate image management project providing a shell for every artifact source and destination, driven by "repository protocol": dir://, docker://, etc. Maybe apt://, dnf://, yum://, wget;//,... This shell drives the corresponding "package manager".

**Comment by Chuxel** [comment]
@PavelSosin-320 Fully understand. We are not focusing on every version of Linux with scripts in this repository is my point. However, the Remote - Containers extension itself works with them just fine.

**Comment by Chuxel** [comment]
Not all were moved to `apt`, but they are all checked against a checksum and also signing where available.
