### ISSUE TITLE
The new Jupyter container definition not include the common script

### ISSUE THREAD

**Issue by eitsupi** [microsoft/vscode-dev-containers#831]
Would you like to include `common-debian.sh`? 
I have used `jupyter/scipy-notebook` (the base image of `jupyter/datascience-notebook`) in Remote-Containers, probably because `openssh-client` is not installed in the image, I couldn't `git push` from the container to the remote repository even with the ssh-agent set.

I think this integrated feature with ssh is one of the great features of VS Code Remote-Containers, so setting up with `common-debian.sh` will improve the user experience. 
https://code.visualstudio.com/docs/remote/containers#_sharing-git-credentials-with-your-container

_Originally posted by @eitsupi in https://github.com/microsoft/vscode-dev-containers/issues/824#issuecomment-826039086_

**Comment by eitsupi** [comment]
@nathancarter
Common scripts are used in many definitions, and various packages can be easily implemented.
The template is a good reference for how to include common scripts in the definition.
https://github.com/microsoft/vscode-dev-containers/tree/master/container-templates/dockerfile

For more information about common scripts, please read the following explanation.
https://github.com/microsoft/vscode-dev-containers/tree/master/script-library

Although it has the disadvantage of taking a little time to install, I found it better to have it installed because it has advantages such as the ability to use ssh in the container.

**Comment by nathancarter** [comment]
Ah, thank you.  After reading the contents of `common-debian.sh`, I can see why it would be so valuable.  I'll add that ASAP.

**Comment by nathancarter** [comment]
I think the above commit fixes the problem.  It required a bit of fiddling, because the `common-debian.sh` script didn't play nice out of the box with the way Jupyter had set up their containers.  But it's good to go now.

Except that I'm kind of new to pushing changes upstream from a fork.  I'm not sure I've followed the correct procedure here.  I updated [my original fork](https://github.com/nathancarter/vscode-dev-containers) with the commit you see above, but when I try to create a second PR from it, it seems to think I want to re-merge ALL the changes again, which is not what we want to do; I think that would apply some diffs twice.

Maybe I wasn't supposed to try to create a second PR from the same fork?  Perhaps I should have pulled other changes downstream into my fork first?  Or created a new fork instead?  Please let me know the appropriate step.  Sorry to ask basic GitHub questions.

**Comment by nathancarter** [comment]
Note that I don't mean that @eitsupi has to answer these questions--perhaps I should be asking @Chuxel instead, who approved the original merge?  Tagging you both just in case.

**Comment by Chuxel** [comment]
> Except that I'm kind of new to pushing changes upstream from a fork. I'm not sure I've followed the correct procedure here. I updated my original fork with the commit you see above, but when I try to create a second PR from it, it seems to think I want to re-merge ALL the changes again, which is not what we want to do; I think that would apply some diffs twice.

@nathancarter Yeah, uou can pull in upstream into your fork's "master" (or main depending on the repo) and creating a new branch from that. Or you can pull in upstream into your existing branch for that matter. 

But, even if you don't git will also do the diffs verses our master when you submit the PR, so only new changes should appear.  No worries there.  We typically "[squash and merge](https://rietta.com/blog/github-merge-types/)" so there won't be excess commits in the tree.

**Comment by nathancarter** [comment]
OK lemme know if I did that correctly.  I merged upstream into my fork, then created a PR that GitHub claims can merge successfully.  Thanks for the assistance!

**Comment by nathancarter** [comment]
Quick question (maybe for @Chuxel ?):  When should users expect to see this new container in the "Open in Container" menu in VS Code itself?  I ask because I'm teaching a course this summer that would love to use it there, and I'm curious whether it will be released in time, or whether I need a backup plan.  Thanks!

**Comment by eitsupi** [comment]
@nathancarter The definitions is included in the Remote-Containers extension and will be reflected in monthly updates.
It seems to be included in today's update (0.177.0)!

![image](https://user-images.githubusercontent.com/50911393/117319801-9b77a800-aec6-11eb-80da-66329be04d8d.png)

**Comment by nathancarter** [comment]
@eitsupi Awesome!  I could have sworn I just looked through the list and didn't see it, but I guess the problem was my eyes, not the list. :)  Thanks!

**Comment by nathancarter** [comment]
Consider it advertised! https://twitter.com/nathancarter5/status/1390330040517230602 Well, okay, to my very limited number of followers.
