### ISSUE TITLE
Remove Node 10 and add Node 16 containers

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-dev-containers#849]
Earlier this month, Node 16 was released, and as of today Node 10 is end-of-life and no longer receiving security updates. We should update the containers accordingly.

**Comment by Chuxel** [comment]
@connor4312 Node 16 is already out and [tracking issue](https://github.com/microsoft/vscode-dev-containers/issues/532) updated to note that node 10 is no longer supported.  :smile: 

See `mcr.microsoft.com/vscode/devcontainers/javascript-node:16`

I left Node 10 in for a bit to let it percolate since 16 just came out, but we'll remove that and Ruby 2.5 before too long. 

I'm giving people some time
