### ISSUE TITLE
Python 3 container : bash never give back shell control after commands end

### ISSUE THREAD

**Issue by playerla** [microsoft/vscode-dev-containers#867]
Hello,

- VSCode Version: 1.56.2 (user setup)
- Local OS Version: Windows 10 with Docker v20.10.6
- Name of Dev Container Definition with Issue: **Python 3 (default)**

Steps to Reproduce:

1. Open an folder empty folder under a git repository
2. New python 3 (default python version without node) dev container 
![image](https://user-images.githubusercontent.com/52384271/118522379-447e9800-b73c-11eb-9bd2-dc5e30853ce8.png)
3. Open a terminal : this take a very long time (up to a minute). Same after each command
![image](https://user-images.githubusercontent.com/52384271/118523057-0e8de380-b73d-11eb-8fa0-e1527f469f8a.png)

**Comment by playerla** [comment]
When I comment the prompt `__bash_prompt` in /home/vscode/.bashrc this timeout is not happening

**Comment by Chuxel** [comment]
@playerla Unfortunately, I'm not able to reproduce this with the same system configuration.  What you describe could in theory be caused if `git status` is slow or not responding.  That can indicate you have another process somewhere on your system indexing your repository and/or locking it.

If you switch to `zsh` do you see the same issue?  (Just type `zsh`.)

**Comment by playerla** [comment]
You're right the prompt is unable to get repositories informations :
- zsh has the same problem
- I made a git init and all work fine. zsh show `main` branch. Bash doesn't even show repo information : 
`vscode ➜ /workspaces/user/Downloads/test $`

Assuming I not want to use a git repository in my container. I had the issue when testing "try remote container" (could be for testing, or under other projects). I think the prompt should not freeze (while trying to display git information from outside the open folder).

**Comment by playerla** [comment]
I have assumed container isolation from host. I wondered why this behaviour : default workspace bind mount the user's home directory to /workspace. Several ways to fix it - using a default container or setting `"HOST_PROJECT_PATH": "${localWorkspaceFolder}"` in devcontainer.json as documented [here](https://code.visualstudio.com/docs/remote/containers-advanced)

**Comment by Chuxel** [comment]
@playerla If you want a separate cloned copy that is isolated from the host, use the **Clone Repository in Container Volume** command instead.

Fundamentally in this case, the prompt can't access `git status`, which is actually quite unusual. Typically tools like Docker Desktop wouldn't cause this to happen unless you were doing something at the exact same time.  This is also  quite common as seen in the ZSH example which every theme in Oh My Zsh! will do (it's just using the standard git library it has).

Commenting out the line in question disables git from appearing in the command line which resolves the problem. Feel free to do that if it suits your needs best.  You can also uninstall `git` which may be safer since extensions and VS Code itself will likely try to interact in the same way.

FWIW - If you do decide to switch between Windows and Linux, be sure you have line ending set properly or you'll see strange behaviors.  VS Code will also try to interact with git via its source control mechanism. The model here is that you use the container like you would your local machine. However, that's not the common use case we're targeting.

**Comment by Chuxel** [comment]
@playerla Oh, one more tip.  If you really want to open a sub-folder without using git, you can use the `workspaceMount` property in `devcontainer.json` (or update your `docker-compose.yml` to mount  point) to mount file system one level up from where your .git folder is located. That's not what VS Code is optimized for (since no git operations or git related extensions will work), but you have that option if you so choose.

**Comment by playerla** [comment]
Docker desktop warns me that sharing files with container may be slow (https://stackoverflow.com/questions/64484579/docker-desktop-filesharing-notification-about-poor-performance). This was my issue, `git status` take 1m23.780s. (instead of ~5s on the host). I close the issue, not related to the container itself.
Thank you for all your advices.
