### ISSUE TITLE
Pre-built Jekyll image

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#919]
Jekyll is used heavily throughout GitHub and generally in static web sites. We can pre-build a version of this image for use.  @2percentsilk and @parkr are discussing requirements.

**Comment by 2percentsilk** [comment]
Moving our convos here versus slack!
@parkr recommended the following initially:
> To be consistent with GitHub Pages, it would be great to install the latest patch version of Ruby 2.7.x, and Jekyll 3.9.x
Dependencies (Jekyll, Ruby, etc) are shared here: https://pages.github.com/versions/
If you install Jekyll 3.9.x and the Gemfile requires 4.x, I think bundle install will ignore the systemwide Jekyll and install the repo-specific one. The only potential problem would be running `jekyll build` – will it pick the pre-installed one or the one in Gemfile? I'd want to test that...

We're now discussing if it makes sense to have an overarching general use Jekyll image as well as a more specific one geared to GitHub pages. My thought is that we want to have one image that ideally works for both so that we don't have to deal with the maintenance of two very similar images and definitions.

The lastest question from @parkr is "could we `alias jekyll="bundle exec jekyll"`? Then we can just run bundle install and it'll automatically use the bundled version"
Pardon my ignorance but would this let us just prebuild one image and have it work for general Jekyll development & Pages? I think our goal is to have images that don't require us to run any installations in the `postCreateCommand` since that's what takes the longest at the moment.

**Comment by parkr** [comment]
If you're worried about post-creation command speed, then the best bet is to install the `github-pages` gem (Jekyll 3.x) and then install Jekyll v4. The most common configurations for Jekyll sites are GitHub Pages and the latest Jekyll. If these are pre-installed on the system, then when `postCreateCommand` runs `bundle install`, it will be very fast.

**Comment by Chuxel** [comment]
//cc: @cmendible as well since we'd be converting that definition into a pre-built one. 

So:

```Dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/ruby:2

# ...

RUN gem install bundler jekyll github-pages
```

...and have a pre-built image with all this in it. Then leave https://github.com/microsoft/vscode-dev-containers/blob/main/containers/jekyll/.devcontainer/post-create.sh largely as-is.

That accurate?

**Comment by Chuxel** [comment]
Put up a PR for review (#929). Let me know if it looks good.

**Comment by Chuxel** [comment]
@parkr Quick check-in: Any feedback here?

**Comment by Chuxel** [comment]
@parkr @2percentsilk Okay, development image is up. See what you think!

```bash
$ docker run -it --rm mcr.microsoft.com/vscode/devcontainers/jekyll:dev bash
```

**Comment by Chuxel** [comment]
I noticed this is using Ruby 3.0 because of #944 - I assume that's a problem?  I'll work on a fix.

**Comment by Chuxel** [comment]
Ok - that's fixed as well.

**Comment by Chuxel** [comment]
This is being published with the v0.188.0 release.  We can adjust from there.

**Comment by kosalanuwan** [comment]
I couldn't get this to work in the Apple M1. Previously worked awesomely in the Intel version.
I suspect it has something to do with the GitHub Pages Dependency versions, to be more specific, the Ruby version.

So switched to the [base.Dockerfile in the ruby devcontainer](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/ruby/.devcontainer/base.Dockerfile) with the 2.7.2 variant and it works.

**Comment by Chuxel** [comment]
@kosalanuwan We do not pre-build M1 images due to docker buildx failures.  See #558
